name: CI CD Pipeline
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Code
              uses: actions/checkout@v4
            - name: Extract commit ID
              id: vars
              run: |
                echo "commit_id=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
                cat $GITHUB_ENV

            - name: Build Docker Image
              run: |
                docker build -t docker.io/moqaddas/demo_frontend:${{ env.commit_id }} .
                echo  ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
                docker push docker.io/moqaddas/demo_frontend:${{ env.commit_id }}
            
    deploy:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: Add SSH Key
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        - name: Configure SSH to disable host key checking
          run: |
                mkdir -p ~/.ssh
                echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


        - name: Deploy to EC2
          run: |
              ssh  -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
                docker pull docker.io/moqaddas/demo_frontend:${{ env.commit_id }}
                docker stop demo_frontend || true
                docker rm demo_frontend || true
                docker run -d --name demo_frontend -p 80:80 docker.io/moqaddas/demo_frontend:${{ env.commit_id }}
              EOF